### ISSUE TITLE
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by BorjaEst** [grycap/im-web#149]
Hi,

I am using the im to deploy an infrastructure but it looks neither the im-web nor the im_client.py can retreive the infrastructure information:

### im configuration (docker-compose):
```yml
  im:
    image: grycap/im:1.9.1  # <-- This is the im container version
    container_name: im
    volumes:
      - ~/Documents/im:/etc/im
    ports:
      - "8899:8899"  
      - "8800:8800"   # <-- API port is map to 8800
```

### im-web configuration:
im_use_rest=true
im_use_ssl=false
im_host=localhost
im_port=8800

When using the im-web I get on the infrastructure page:
`Error: Code: 0. Error connecting to URL: http://localhost:8800/infrastructures`

### im_client.py configuration:
The configuration on the im_client.cfg
```sh
[im_client]
restapi_url=http://172.17.0.1:8800  # <-- inside docker, so this addr is localhost
auth_file=auth.dat
verify-ssl=false
#xmlrpc_ssl_ca_certs=/tmp/pki/ca-chain.pem
```

When using the im_client.py I get:
 ```sh
root@509881c7fbd6:/home# im_client.py create tosca-templates/simple-node.yml 
Connected with: http://172.17.0.1:8800
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

## Notes with telnet:
(base) borja@eoan-dev:~$ telnet localhost 8800
Trying 127.0.0.1...
Connected to localhost.
Connection closed by foreign host.

(base) borja@eoan-dev:~$ telnet localhost 8899
Trying 127.0.0.1...
Connected to localhost.
telnet> close
Connection closed.

(base) borja@eoan-dev:~$ telnet localhost 8805 # <-- sample not opened
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

BR Borja

**Comment by micafer** [comment]
I see that you are mounting the /etc/im. 
Could you show me the im.cfg file that should be located in you local machine at: ~/Documents/im?
If there are no im.cfg file in this directory REST API is disabled by default.

**Comment by BorjaEst** [comment]
This is the current directory status:
```
~/Documents/im$ tree etc/
etc/
└── inf.dat
0 directories, 1 file
```
You are right, there is no "im.cfg". However if I try the following docker-compose:
```yml
  im:
    image: grycap/im:1.9.1  # <-- This is the im container version
    container_name: im
    ports:
      - "8899:8899"  
      - "8800:8800"   # <-- API port is map to 8800
```
I am still receiving the same error in the im-web:
```
Error: Code: 0. Error connecting to URL: http://localhost:8800/infrastructures
```

**Comment by micafer** [comment]
Try to add again the volume, and copy in the : ~/Documents/im dir this file: https://github.com/grycap/im/blob/master/etc/im.cfg

**Comment by BorjaEst** [comment]
So I changed the location to something internal to the project and added the file:
### docker-compose
```yml
services:
  im:
    image: grycap/im:1.9.1  # <-- This is the im container version
    container_name: im
    env_file:
        - "im/im.env"
    volumes:
      - ./im/etc/im:/etc/im #<- Location for external im.cfg
    ports:
      - "8800:8800" # <-- API port is map to 8800
  im-web:
    image: grycap/im-web
    depends_on: 
      - im
    container_name: im-web
    env_file:
      - "im-web/im-web.env"
    ports: 
      - "80:80"
    links:
      - im:im grycap/im-web
```
### Files located
```sh
$ tree im/etc/
im/etc/
└── im
    ├── im.cfg
    └── inf.dat
1 directory, 2 files
```
I checked the configuration is inside by:
```
$ docker exec -it im cat /etc/im/im.cfg
# IM - Infrastructure Manager
# Copyright (C) 2011 - GRyCAP - Universitat Politecnica de Valencia
...
[im]
...
# REST API Info
ACTIVATE_REST = True
REST_PORT = 8800
REST_ADDRESS = 0.0.0.0
...
```

However it is still the same issue:
`Error: Code: 0. Error connecting to URL: http://localhost:8800/infrastructures`

**Comment by BorjaEst** [comment]
At the end thanks to Miguel the issue was solved.

In the im-web configuration it is needed to use 'im' as im_host. 'localhost' would point to the container itself (so logically cannot connect to the URL):
### im-web configuration:
im_use_rest=true
im_use_ssl=false
im_host= ~~localhost~~ im
im_port=8800

> Note the link at docker-compose (so the im is reached):
### docker-compose
```yml
services:
  im:
    ...
  im-web:
    ...
    links:
      - im:im grycap/im-web
```
BR, Borja
